[build-system]
requires = ['setuptools']
build-backend = 'setuptools.build_meta'

[project]
name = 'dda_atmos'
version = '0.0.1'
dependencies = [
    'numpy',
    'scipy',
    'scikit-image'
]

[tool.setuptools.packages.find]